### ISSUE TITLE
Wrong header

### ISSUE THREAD

**Issue by options2015** [FocSon/OsmosisArbitrage#5]
Getting an error as below

```
732/734
733/734
734/734
file://OsmosisArbitrage-main/src/SignUtils.js:141
    return res.block.header.height;
                     ^

TypeError: Cannot read properties of undefined (reading 'header')
    at getLatestBlock (file://OsmosisArbitrage-main/src/SignUtils.js:141:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async checkAllRoutes (file://OsmosisArbitrage-main/src/SignUtils.js:23:17)
    at async main (file://OsmosisArbitrage-main/src/Main.js:13:5)

Node.js v20.15.1
```

**Comment by FocSon** [comment]
Hello !

Yep, i added an edit to the readme :

Since this bot hasn't been maintained, a lot of network update happened. You'll probably encounter some errors running this bot. If you want to deep in it and update it, don't hasitate to make a PR, I will watch about it but i don't plan to maintain it myself.

This is probably due to an update of the way to get the blockchain height with OsmoJS.
See here [OsmoJS documentation](https://github.com/osmosis-labs/osmojs)

I am really sorry about it .

**Comment by options2015** [comment]
Thank you very much for your help. How much money should I hold in different symbols/pairs to run the bot?

**Comment by options2015** [comment]
```
BroadcastTxError: Broadcasting transaction failed with code 13 (codespace: sdk). Log: insufficient fees; got: 1252uosmo which converts to 1252uosmo>
    at SigningStargateClient.broadcastTx (/root/osmosis-arbitrage/node_modules/osmojs/node_modules/@cosmjs/stargate/build/stargateclient.js:267:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 13,
  codespace: 'sdk',
  log: 'insufficient fees; got: 1252uosmo which converts to 1252uosmo. required: 25000uosmo: insufficient fee'
}

```
